name: quiz_app
description: A Flutter quiz application with timer functionality.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.1.1
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
